### PR TITLE
Tighten margins on the login page header; fix exhaustive deps warnings

### PR DESCRIPTION
**Pull request by denniskigen**
This PR:

- Adjusts the margins on the login page welcome header, as well as reducing the size of the welcome text and the `Location` heading at the top of the location picker card.
- Also fixes a couple of React hooks exhaustive dependencies warnings that were being flagged on running lint.

Before:
Screenshot 2020-12-16 at 09 18 12

After:
Screenshot 2020-12-16 at 09 16 38

### CODE REVIEW

**Comment by jonathandick** [comment]
@nmalyschkin aee you able to review?

**Comment by nmalyschkin** [comment]
This is probably not in the context of this PR but I've noticed that the lower left corners of the card has a different radius than the other corners, is this intentional?

**Comment by denniskigen** [comment]
@nmalyschkin likely unintentional. This card is based on the SummaryCard implementation in the old designs that we're moving away from. AFAIK we don't have designs for the login page though I imagine it's a matter of time before they're available and we can then migrate the other MFs to use Carbon as well.

**Review by nmalyschkin — APPROVED** [review]
Looks good

**Pull request merged**
